// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS.Reaction;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FConfiguration extends Table {
  public static FConfiguration getRootAsFConfiguration(ByteBuffer _bb) { return getRootAsFConfiguration(_bb, new FConfiguration()); }
  public static FConfiguration getRootAsFConfiguration(ByteBuffer _bb, FConfiguration obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FConfiguration __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String configurableName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer configurableNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public double configurableValue() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createFConfiguration(FlatBufferBuilder builder,
      int configurable_nameOffset,
      double configurable_value) {
    builder.startObject(2);
    FConfiguration.addConfigurableValue(builder, configurable_value);
    FConfiguration.addConfigurableName(builder, configurable_nameOffset);
    return FConfiguration.endFConfiguration(builder);
  }

  public static void startFConfiguration(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addConfigurableName(FlatBufferBuilder builder, int configurableNameOffset) { builder.addOffset(0, configurableNameOffset, 0); }
  public static void addConfigurableValue(FlatBufferBuilder builder, double configurableValue) { builder.addDouble(1, configurableValue, 0.0); }
  public static int endFConfiguration(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // configurable_name
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) { return compareStrings(__offset(4, o1, _bb), __offset(4, o2, _bb), _bb); }

  public static FConfiguration __lookup_by_key(int vectorLocation, String key, ByteBuffer bb) {
    byte[] byteKey = key.getBytes(Table.UTF8_CHARSET.get());
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = compareStrings(__offset(4, bb.capacity() - tableOffset, bb), byteKey, bb);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new FConfiguration().__assign(tableOffset, bb);
      }
    }
    return null;
  }
}

