// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

public final class FByteDataType {
  private FByteDataType() { }
  public static final byte PNG = 0;
  public static final byte JPEG = 1;
  public static final byte Other = 2;

  public static final String[] names = { "PNG", "JPEG", "Other", };

  public static String name(int e) { return names[e]; }
}

