// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FByteArray extends Table {
  public static FByteArray getRootAsFByteArray(ByteBuffer _bb) { return getRootAsFByteArray(_bb, new FByteArray()); }
  public static FByteArray getRootAsFByteArray(ByteBuffer _bb, FByteArray obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FByteArray __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int bytes(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int bytesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer bytesAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int type() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createFByteArray(FlatBufferBuilder builder,
      int bytesOffset,
      int type) {
    builder.startObject(2);
    FByteArray.addBytes(builder, bytesOffset);
    FByteArray.addType(builder, type);
    return FByteArray.endFByteArray(builder);
  }

  public static void startFByteArray(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addBytes(FlatBufferBuilder builder, int bytesOffset) { builder.addOffset(0, bytesOffset, 0); }
  public static int createBytesVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startBytesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(1, (byte)type, (byte)0); }
  public static int endFByteArray(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // bytes
    return o;
  }
}

