// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FDouble extends Table {
  public static FDouble getRootAsFDouble(ByteBuffer _bb) { return getRootAsFDouble(_bb, new FDouble()); }
  public static FDouble getRootAsFDouble(ByteBuffer _bb, FDouble obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FDouble __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FVector2 vec2() { return vec2(new FVector2()); }
  public FVector2 vec2(FVector2 obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public FRange xRange() { return xRange(new FRange()); }
  public FRange xRange(FRange obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public FRange yRange() { return yRange(new FRange()); }
  public FRange yRange(FRange obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startFDouble(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addVec2(FlatBufferBuilder builder, int vec2Offset) { builder.addStruct(0, vec2Offset, 0); }
  public static void addXRange(FlatBufferBuilder builder, int xRangeOffset) { builder.addStruct(1, xRangeOffset, 0); }
  public static void addYRange(FlatBufferBuilder builder, int yRangeOffset) { builder.addStruct(2, yRangeOffset, 0); }
  public static int endFDouble(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

