// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FEulerTransform extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FEulerTransform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FVector3 position() { return position(new FVector3()); }
  public FVector3 position(FVector3 obj) { return obj.__assign(bb_pos + 0, bb); }
  public FVector3 rotation() { return rotation(new FVector3()); }
  public FVector3 rotation(FVector3 obj) { return obj.__assign(bb_pos + 24, bb); }
  public FVector3 direction() { return direction(new FVector3()); }
  public FVector3 direction(FVector3 obj) { return obj.__assign(bb_pos + 48, bb); }

  public static int createFEulerTransform(FlatBufferBuilder builder, double position_x, double position_y, double position_z, double rotation_x, double rotation_y, double rotation_z, double direction_x, double direction_y, double direction_z) {
    builder.prep(8, 72);
    builder.prep(8, 24);
    builder.putDouble(direction_z);
    builder.putDouble(direction_y);
    builder.putDouble(direction_x);
    builder.prep(8, 24);
    builder.putDouble(rotation_z);
    builder.putDouble(rotation_y);
    builder.putDouble(rotation_x);
    builder.prep(8, 24);
    builder.putDouble(position_z);
    builder.putDouble(position_y);
    builder.putDouble(position_x);
    return builder.offset();
  }
}

