// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FQuadruple extends Table {
  public static FQuadruple getRootAsFQuadruple(ByteBuffer _bb) { return getRootAsFQuadruple(_bb, new FQuadruple()); }
  public static FQuadruple getRootAsFQuadruple(ByteBuffer _bb, FQuadruple obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FQuadruple __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FQuaternion quat() { return quat(new FQuaternion()); }
  public FQuaternion quat(FQuaternion obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public FRange xRange() { return xRange(new FRange()); }
  public FRange xRange(FRange obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public FRange yRange() { return yRange(new FRange()); }
  public FRange yRange(FRange obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public FRange zRange() { return zRange(new FRange()); }
  public FRange zRange(FRange obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public FRange wRange() { return wRange(new FRange()); }
  public FRange wRange(FRange obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startFQuadruple(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addQuat(FlatBufferBuilder builder, int quatOffset) { builder.addStruct(0, quatOffset, 0); }
  public static void addXRange(FlatBufferBuilder builder, int xRangeOffset) { builder.addStruct(1, xRangeOffset, 0); }
  public static void addYRange(FlatBufferBuilder builder, int yRangeOffset) { builder.addStruct(2, yRangeOffset, 0); }
  public static void addZRange(FlatBufferBuilder builder, int zRangeOffset) { builder.addStruct(3, zRangeOffset, 0); }
  public static void addWRange(FlatBufferBuilder builder, int wRangeOffset) { builder.addStruct(4, wRangeOffset, 0); }
  public static int endFQuadruple(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // quat
    return o;
  }
}

