// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FQuaternionTransform extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FQuaternionTransform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FVector3 position() { return position(new FVector3()); }
  public FVector3 position(FVector3 obj) { return obj.__assign(bb_pos + 0, bb); }
  public FQuaternion rotation() { return rotation(new FQuaternion()); }
  public FQuaternion rotation(FQuaternion obj) { return obj.__assign(bb_pos + 24, bb); }

  public static int createFQuaternionTransform(FlatBufferBuilder builder, double position_x, double position_y, double position_z, double rotation_x, double rotation_y, double rotation_z, double rotation_w) {
    builder.prep(8, 56);
    builder.prep(8, 32);
    builder.putDouble(rotation_w);
    builder.putDouble(rotation_z);
    builder.putDouble(rotation_y);
    builder.putDouble(rotation_x);
    builder.prep(8, 24);
    builder.putDouble(position_z);
    builder.putDouble(position_y);
    builder.putDouble(position_x);
    return builder.offset();
  }
}

