// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FSingle extends Table {
  public static FSingle getRootAsFSingle(ByteBuffer _bb) { return getRootAsFSingle(_bb, new FSingle()); }
  public static FSingle getRootAsFSingle(ByteBuffer _bb, FSingle obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FSingle __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double value() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public FRange range() { return range(new FRange()); }
  public FRange range(FRange obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startFSingle(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addValue(FlatBufferBuilder builder, double value) { builder.addDouble(0, value, 0.0); }
  public static void addRange(FlatBufferBuilder builder, int rangeOffset) { builder.addStruct(1, rangeOffset, 0); }
  public static int endFSingle(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

