// automatically generated by the FlatBuffers compiler, do not modify

package Neodroid.FBS;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FValuedVector3Point extends Table {
  public static FValuedVector3Point getRootAsFValuedVector3Point(ByteBuffer _bb) { return getRootAsFValuedVector3Point(_bb, new FValuedVector3Point()); }
  public static FValuedVector3Point getRootAsFValuedVector3Point(ByteBuffer _bb, FValuedVector3Point obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FValuedVector3Point __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double val() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public FVector3 point() { return point(new FVector3()); }
  public FVector3 point(FVector3 obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startFValuedVector3Point(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addVal(FlatBufferBuilder builder, double val) { builder.addDouble(0, val, 0.0); }
  public static void addPoint(FlatBufferBuilder builder, int pointOffset) { builder.addStruct(1, pointOffset, 0); }
  public static int endFValuedVector3Point(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

